name: Cppcheck CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Cppcheck on srcs (C++98 style)
        uses: deep5050/cppcheck-action@v3.0
        continue-on-error: true  # Don't stop job immediately
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          std: c++03
          output_file: cppcheck-report.txt
          other_options: srcs/ --enable=all --inconclusive --quiet
          check_library: disable
          skip_preprocessor: disable
          enable: all
          exclude_check: disable
          inconclusive: enable
          inline_suppression: disable
          force_language: disable
          force: disable
          max_ctu_depth: disable
          platform: disable

      - name: Upload Cppcheck report artifact
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck-report
          path: cppcheck-report.txt

      - name: Add Cppcheck report link to PR summary
        if: github.event_name == 'pull_request'
        run: |
          echo "Cppcheck full report available [here](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID})" >> $GITHUB_STEP_SUMMARY

      - name: Fail job if Cppcheck found errors
        if: always()  # always runs, even if previous step failed
        run: |
          if grep -q '\[error\]' cppcheck-report.txt; then
            echo "Cppcheck found errors. Failing the job."
            exit 1
          fi
